spring:
  application:
    name: dispatcher
  devtools:
    restart:
      enabled: false

  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${DISPATCHER_PORT}

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
