spring:
  application:
    name: dispatcher
  devtools:
    restart:
      enabled: false

  rabbitmq:
    port: ${RABBIT_PORT}
    host: ${RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE}

server:
  port: ${DISPATCHER_PORT:8084}

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
