spring:
  application:
    name: node

  rabbitmq:
    port: ${RABBIT_PORT:5673}
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:lord}
    password: ${RABBIT_PASSWORD:admin}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE:message_update}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE:message_answer}

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:jkgkhfkdkl}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${NODE_PORT:8085}
