--liquibase formatted sql

--changeset mkilord:001-init
create table users
(
    telegram_id bigint primary key,
    chat_id     bigint      not null,
    username    varchar(64),
    role        varchar(16) not null,
    first_name  varchar(50),
    last_name   varchar(50),
    middle_name varchar(50),
    email       varchar(254),
    phone       varchar(16)
);
create index users_username_idx on users (lower(username));
create index users_role_idx on users (role);

create table club
(
    id          bigint generated by default as identity primary key,
    name        varchar(50)  not null,
    description varchar(250) not null
);

create table club_subscriber
(
    club_id bigint not null references club (id) on delete cascade,
    user_id bigint not null references users (telegram_id) on delete cascade,
    primary key (club_id, user_id)
);

create table club_rating
(
    club_id bigint   not null references club (id) on delete cascade,
    user_id bigint   not null references users (telegram_id) on delete cascade,
    rating  integer  not null check (rating between 1 and 10),
    primary key (club_id, user_id)
);

create table meet
(
    id        bigint generated by default as identity primary key,
    club_id   bigint       not null references club (id) on delete cascade,
    name      varchar(250) not null,
    meet_date date         not null,
    meet_time time         not null,
    status    varchar(16)  not null
);
create index meet_club_status_idx on meet (club_id, status, meet_date);

create table meet_participant
(
    meet_id bigint not null references meet (id) on delete cascade,
    user_id bigint not null references users (telegram_id) on delete cascade,
    primary key (meet_id, user_id)
);
create index meet_participant_user_idx on meet_participant (user_id);

create table dialog_state
(
    chat_id        bigint primary key,
    reply_id       varchar(64),
    dialog_values  jsonb       not null default '{}'::jsonb,
    updated_at     timestamptz not null default now()
);
create index dialog_state_updated_at_idx on dialog_state (updated_at);

create table processed_update
(
    update_id    bigint primary key,
    processed_at timestamptz not null default now()
);
create index processed_update_processed_at_idx on processed_update (processed_at);
